name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Roda sempre que der push na main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file from Secrets
        # 1. Definimos as variáveis de ambiente do shell a partir dos Secrets
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" > .env
          echo "SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY" >> .env

      - name: Verify .env Content (SUCCESS)
        run: cat .env

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          # flutter-version: '3.19.0' # Opcional: Travar versão se quiser

      - name: Install dependencies
        run: flutter pub get

      # IMPORTANTE: Substitua 'meu_curriculo_flutter' pelo nome EXATO do seu repositório
      - name: Build Web
        run: flutter build web --release --base-href "/meu_curriculo_flutter/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
